const bcrypt=require('bcryptjs');
const {DISTRICTS}=require('../config/districts');
const M={
 District:require('../models/District'),Incident:require('../models/Incident'),Resource:require('../models/Resource'),Shelter:require('../models/Shelter'),Alert:require('../models/Alert'),RoadBlock:require('../models/RoadBlock'),RiverGauge:require('../models/RiverGauge'),Infrastructure:require('../models/Infrastructure'),FloodZone:require('../models/FloodZone'),User:require('../models/User'),Notification:require('../models/Notification'),Evacuation:require('../models/Evacuation'),WeatherSnapshot:require('../models/WeatherSnapshot'),EmergencyContact:require('../models/EmergencyContact')
};
const types=['PERSON_TRAPPED','MEDICAL_EMERGENCY','FLOODED_HOUSE','ROAD_BLOCKED','WATERLOGGING','MISSING_PERSON','INFRASTRUCTURE_DAMAGE','EVACUATION_REQUEST'];
const resourceTypes=['RESCUE_TEAM','BOAT','AMBULANCE','FIRE_UNIT','MEDICAL_TEAM'];
const point=(c,i,spread=.12)=>[c.lat+(((i*37)%100)/100-.5)*spread,c.lng+(((i*61)%100)/100-.5)*spread];
const poly=(c,i)=>{const d=.035+(i%3)*.012;return [[[c.lng-d,c.lat-d],[c.lng+d,c.lat-d*.5],[c.lng+d*.6,c.lat+d],[c.lng-d*.8,c.lat+d*.7],[c.lng-d,c.lat-d]]]};
function score(x){let s=({PERSON_TRAPPED:25,MEDICAL_EMERGENCY:22,MISSING_PERSON:18,FLOODED_HOUSE:12,EVACUATION_REQUEST:14,INFRASTRUCTURE_DAMAGE:8,ROAD_BLOCKED:6,WATERLOGGING:4}[x.type]||3),r=[{label:`Incident type: ${x.type.replaceAll('_',' ')}`,points:s}];for(const [k,l,p] of [['trapped','People trapped',25],['elderly','Elderly present',20],['disabled','Accessibility / disability need',15],['medicalNeed','Medical concern',20],['children','Children present',8]])if(x[k]){s+=p;r.push({label:l,points:p})}const people=Math.max(1,+x.peopleAffected||1),pp=people>=10?20:people>=6?17:people>=3?10:4;s+=pp;r.push({label:`${people} people affected`,points:pp});s+=Math.min(5,Math.max(1,+x.floodSeverity||1))*3;r.push({label:`Flood severity ${x.floodSeverity}/5`,points:Math.min(5,Math.max(1,+x.floodSeverity||1))*3});s=Math.min(100,s);return{priorityScore:s,severity:s>=76?'CRITICAL':s>=51?'HIGH':s>=26?'MODERATE':'LOW',priorityReasons:r}}
async function resetAndSeed(){for(const m of Object.values(M))await m.deleteMany({});return seed(false)}
async function seed(reset=false){
 if(reset)for(const m of Object.values(M))await m.deleteMany({});
 if(await M.District.countDocuments()===0)await M.District.insertMany(DISTRICTS);
 if(await M.User.countDocuments()===0){const pass=bcrypt.hashSync('floodguard123',10);await M.User.insertMany([
  ['System Administrator','admin@floodguard.gov','ADMIN'],['District Officer R. Sharma','officer@floodguard.gov','DISTRICT_OFFICER'],['Field Responder A. Khan','responder@floodguard.gov','FIELD_RESPONDER'],['Citizen User','citizen@floodguard.gov','CITIZEN']].map(([name,email,role])=>({name,email,password:pass,role,district:'Dibrugarh',state:'Assam'})))}
 if(await M.EmergencyContact.countDocuments()===0)await M.EmergencyContact.insertMany([
  {category:'National Emergency',name:'Emergency Response Support',phone:'112',district:'ALL',state:'India',isDemo:false},
  {category:'Ambulance',name:'Emergency Medical',phone:'108',district:'ALL',state:'India',isDemo:false},
  {category:'Police',name:'Police Emergency',phone:'100',district:'ALL',state:'India',isDemo:false},
  {category:'Fire',name:'Fire & Rescue',phone:'101',district:'ALL',state:'India',isDemo:false},
  {category:'Assam Flood Control',name:'District Flood Control Room',phone:'1070',district:'ALL',state:'Assam',isDemo:true}
 ]);
 for(const d of DISTRICTS){
  const existing=await M.Incident.countDocuments({state:d.state,district:d.name});if(existing>0)continue;const c=d.center;
  const shelters=[];for(let i=1;i<=10;i++){const [lat,lng]=point(c,i,.10),capacity=300+(i%5)*75,occupancy=Math.min(capacity-20,75+i*19+(d.name==='Dibrugarh'?35:0));shelters.push({name:`${d.name} Relief Shelter ${String(i).padStart(2,'0')}`,latitude:lat,longitude:lng,capacity,occupancy,food:true,water:true,medical:i%2===0,accessibility:i%3===0,contact:'+91 00000 00000',status:occupancy>=capacity*.8?'NEAR_CAPACITY':'OPEN',district:d.name,state:d.state,sourceType:'DEMO',sourceName:'FloodGuard Seed'});}await M.Shelter.insertMany(shelters);
  const resources=[];for(let i=1;i<=18;i++){const [lat,lng]=point(c,100+i,.11);resources.push({name:`${d.name} Response Unit ${String(i).padStart(2,'0')}`,type:resourceTypes[(i-1)%resourceTypes.length],latitude:lat,longitude:lng,status:i%9===0?'BUSY':i%13===0?'OFFLINE':'AVAILABLE',capacity:i%5===0?10:5,equipment:['First Aid','Radio','Life Jacket'],contact:'+91 00000 00000',district:d.name,state:d.state,sourceType:'DEMO',sourceName:'FloodGuard Seed'});}await M.Resource.insertMany(resources);
  const incidents=[];const count=d.name==='Dibrugarh'?35:20;for(let i=1;i<=count;i++){const t=types[(i-1)%types.length],[lat,lng]=point(c,200+i,.14),x={code:`${d.name.slice(0,3).toUpperCase()}-${String(i).padStart(4,'0')}`,type:t,description:`${t.replaceAll('_',' ')} reported near ${d.zones[i%d.zones.length]}. Response coordination required.`,latitude:lat,longitude:lng,location:d.zones[i%d.zones.length],peopleAffected:1+(i%11),children:i%7===0,elderly:i%5===0,disabled:i%11===0,medicalNeed:t==='MEDICAL_EMERGENCY'||i%13===0,trapped:t==='PERSON_TRAPPED',floodSeverity:3+(i%3),district:d.name,state:d.state,zone:d.zones[i%d.zones.length],source:'FloodGuard Seed',sourceType:'DEMO',sourceName:'FloodGuard Seed',verificationStatus:i%4===0?'VERIFIED':'UNVERIFIED',status:i%9===0?'IN_PROGRESS':i%7===0?'ASSIGNED':'VERIFIED',timeline:[{status:'VERIFIED',note:'Seeded operational scenario',by:'FloodGuard Seed'}]};Object.assign(x,score(x));incidents.push(x)}await M.Incident.insertMany(incidents);
  const roads=[];for(let i=1;i<=22;i++){const [lat,lng]=point(c,400+i,.15);roads.push({name:`${d.name} Road Segment R-${String(i).padStart(2,'0')}`,latitude:lat,longitude:lng,status:i%8===0?'BLOCKED':i%11===0?'FLOODED':'OPEN',note:i%8===0?'Water over road / vehicle access restricted':'Operational demo road condition',district:d.name,state:d.state,sourceType:'DEMO',sourceName:'FloodGuard Seed'});}await M.RoadBlock.insertMany(roads);
  await M.RiverGauge.insertMany(d.rivers.map((river,i)=>({district:d.name,state:d.state,station:d.cwcSites[i]||`${d.name} Gauge`,river,latitude:c.lat+i*.025,longitude:c.lng+i*.02,waterLevel:+((river==='Brahmaputra'?98.7:74.2)+i*1.4*10).toFixed(1),warningLevel:river==='Brahmaputra'?99.2:75,dangerLevel:river==='Brahmaputra'?100.2:76,trend:i%2?'STEADY':'RISING',floodStatus:i%2?'ABOVE NORMAL':'WARNING',sourceType:'CACHED',sourceName:'CWC Flood Forecasting Network',sourceUrl:'https://ffs.india-water.gov.in/#/',lastFetchedAt:new Date()})));
  const infra=[];for(let i=1;i<=4;i++){for(const [type,label,offset] of [['HOSPITAL','District Hospital',600],['POLICE','Police Station',650],['FIRE_STATION','Fire & Emergency Station',700]]){const [lat,lng]=point(c,offset+i,.12);infra.push({name:`${d.name} ${label} ${i}`,type,latitude:lat,longitude:lng,status:'OPERATIONAL',district:d.name,state:d.state,sourceType:'DEMO',sourceName:'FloodGuard Seed'})}}await M.Infrastructure.insertMany(infra);
  await M.FloodZone.insertMany([1,2,3,4].map(i=>({name:`${d.name} Flood Affected Zone ${i}`,district:d.name,state:d.state,severity:i===1?'CRITICAL':i===2?'HIGH':'MODERATE',geometry:{type:'Polygon',coordinates:poly(c,i)},sourceType:'DEMO',sourceName:'FloodGuard Seed'})));
  await M.Alert.insertMany([{externalId:`DEMO-${d.state}-${d.name}-01`,title:`${d.name} flood situation watch`,description:`Demo operational advisory: monitor river levels, low-lying areas, road access and relief capacity.`,severity:'WARNING',district:d.name,state:d.state,affectedArea:d.zones.slice(0,3).join(', '),issuedAt:new Date(Date.now()-45*60000),expiresAt:new Date(Date.now()+8*3600000),officialUrl:'https://sachet.ndma.gov.in/',sourceType:'DEMO',source:'FloodGuard Seed',sourceUrl:'https://sachet.ndma.gov.in/',verificationStatus:'DEMO'},{externalId:`DEMO-${d.state}-${d.name}-02`,title:'Heavy rainfall preparedness notice',description:'Demo alert used when public feeds are unavailable; not an official government warning.',severity:'WATCH',district:d.name,state:d.state,issuedAt:new Date(Date.now()-2*3600000),expiresAt:new Date(Date.now()+18*3600000),sourceType:'DEMO',source:'FloodGuard Seed',verificationStatus:'DEMO'}]);
  await M.WeatherSnapshot.create({district:d.name,state:d.state,temperature:d.state==='Assam'?28:30,rainfallMm:d.state==='Assam'?38:12,precipitationProbability:d.state==='Assam'?72:38,humidity:d.state==='Assam'?84:64,windSpeed:12,condition:d.state==='Assam'?'Heavy Rain':'Cloudy',warningLevel:d.state==='Assam'?'WARNING':'WATCH',sourceType:'DEMO',source:'FloodGuard Seed / fallback',sourceUrl:'https://open-meteo.com/',forecast:Array.from({length:7},(_,i)=>({day:i===0?'Today':['Tomorrow','Fri','Sat','Sun','Mon','Tue'][i-1]||`Day ${i+1}`,rainfallMm:Math.max(4,38-i*4),tempMax:30+i%3,tempMin:24+i%2,precipitationProbability:72-i*6}))});
 }
 return {seeded:true};
}
module.exports={seed,resetAndSeed};
