const {DISTRICTS}=require('../config/districts');
let ready=false;const store={};const id=()=>Math.random().toString(36).slice(2,10);
const types=['PERSON_TRAPPED','MEDICAL_EMERGENCY','FLOODED_HOUSE','ROAD_BLOCKED','WATERLOGGING','MISSING_PERSON','INFRASTRUCTURE_DAMAGE','EVACUATION_REQUEST'];
const resources=['RESCUE_TEAM','BOAT','AMBULANCE','FIRE_UNIT','MEDICAL_TEAM'];
const point=(c,i,s=.12)=>({latitude:+(c.lat+(((i*37)%100)/100-.5)*s).toFixed(6),longitude:+(c.lng+(((i*61)%100)/100-.5)*s).toFixed(6)});
function score(x){let n=({PERSON_TRAPPED:25,MEDICAL_EMERGENCY:22,MISSING_PERSON:18,FLOODED_HOUSE:12,EVACUATION_REQUEST:14,INFRASTRUCTURE_DAMAGE:8,ROAD_BLOCKED:6,WATERLOGGING:4}[x.type]||3),re=[];if(x.trapped){n+=25;re.push({label:'People trapped',points:25})}if(x.elderly){n+=20;re.push({label:'Elderly present',points:20})}if(x.disabled){n+=15;re.push({label:'Accessibility / disability need',points:15})}if(x.medicalNeed){n+=20;re.push({label:'Medical concern',points:20})}if(x.children){n+=8;re.push({label:'Children present',points:8})}const p=x.peopleAffected>=10?20:x.peopleAffected>=6?17:x.peopleAffected>=3?10:4;n+=p;re.push({label:`${x.peopleAffected} people affected`,points:p});const f=x.floodSeverity*3;n+=f;re.push({label:`Flood severity ${x.floodSeverity}/5`,points:f});n=Math.min(100,n);return{priorityScore:n,severity:n>=76?'CRITICAL':n>=51?'HIGH':n>=26?'MODERATE':'LOW',priorityReasons:[{label:`Incident type: ${x.type.replaceAll('_',' ')}`,points:({PERSON_TRAPPED:25,MEDICAL_EMERGENCY:22,MISSING_PERSON:18,FLOODED_HOUSE:12,EVACUATION_REQUEST:14,INFRASTRUCTURE_DAMAGE:8,ROAD_BLOCKED:6,WATERLOGGING:4}[x.type]||3)},...re]}}
function initDistrict(d){const c=d.center,x={district:{...d},incidents:[],resources:[],shelters:[],alerts:[],roads:[],gauges:[],infrastructure:[],evacuations:[],floodzones:[],notifications:[],reports:[],weather:{district:d.name,state:d.state,temperature:d.state==='Assam'?28:30,rainfallMm:d.state==='Assam'?38:12,precipitationProbability:d.state==='Assam'?72:38,humidity:d.state==='Assam'?84:64,windSpeed:12,condition:d.state==='Assam'?'Heavy Rain':'Cloudy',warningLevel:d.state==='Assam'?'WARNING':'WATCH',sourceType:'DEMO',source:'FloodGuard Seed / fallback',forecast:Array.from({length:7},(_,i)=>({day:i===0?'Today':`Day ${i+1}`,rainfallMm:Math.max(4,38-i*4),tempMax:30+i%3,tempMin:24+i%2,precipitationProbability:72-i*6}))}};
 for(let i=1;i<=10;i++){const p=point(c,i,.1),capacity=300+(i%5)*75,occupancy=Math.min(capacity-20,75+i*19+(d.name==='Dibrugarh'?35:0));x.shelters.push({_id:id(),name:`${d.name} Relief Shelter ${String(i).padStart(2,'0')}`,...p,capacity,occupancy,food:true,water:true,medical:i%2===0,accessibility:i%3===0,contact:'112',status:occupancy>=capacity*.8?'NEAR_CAPACITY':'OPEN',state:d.state,district:d.name,sourceType:'DEMO',sourceName:'FloodGuard Seed'})}
 for(let i=1;i<=18;i++){const p=point(c,100+i,.11);x.resources.push({_id:id(),name:`${d.name} Response Unit ${String(i).padStart(2,'0')}`,type:resources[(i-1)%resources.length],...p,status:i%9===0?'BUSY':i%13===0?'OFFLINE':'AVAILABLE',capacity:i%5===0?10:5,equipment:['First Aid','Radio','Life Jacket'],district:d.name,state:d.state,sourceType:'DEMO',sourceName:'FloodGuard Seed'})}
 const count=d.name==='Dibrugarh'?35:20;for(let i=1;i<=count;i++){const type=types[(i-1)%types.length],p=point(c,200+i,.14),z=d.zones[i%d.zones.length],o={_id:id(),code:`${d.name.slice(0,3).toUpperCase()}-${String(i).padStart(4,'0')}`,type,description:`${type.replaceAll('_',' ')} reported near ${z}. Response coordination required.`,...p,location:z,peopleAffected:1+(i%11),children:i%7===0,elderly:i%5===0,disabled:i%11===0,medicalNeed:type==='MEDICAL_EMERGENCY'||i%13===0,trapped:type==='PERSON_TRAPPED',floodSeverity:3+(i%3),district:d.name,state:d.state,zone:z,source:'FloodGuard Seed',sourceType:'DEMO',sourceName:'FloodGuard Seed',verificationStatus:i%4===0?'VERIFIED':'UNVERIFIED',status:i%9===0?'IN_PROGRESS':i%7===0?'ASSIGNED':'VERIFIED',createdAt:new Date(Date.now()-i*360000)};Object.assign(o,score(o));x.incidents.push(o)}
 for(let i=1;i<=22;i++){const p=point(c,400+i,.15);x.roads.push({_id:id(),name:`${d.name} Road Segment R-${String(i).padStart(2,'0')}`,...p,status:i%8===0?'BLOCKED':i%11===0?'FLOODED':'OPEN',note:i%8===0?'Water over road / vehicle access restricted':'Operational demo road condition',district:d.name,state:d.state,sourceType:'DEMO',sourceName:'FloodGuard Seed'})}
 d.rivers.forEach((river,i)=>x.gauges.push({_id:id(),station:d.cwcSites[i]||`${d.name} Gauge`,river,latitude:c.lat+i*.025,longitude:c.lng+i*.02,waterLevel:+((river==='Brahmaputra'?98.7:74.2)+i*14).toFixed(1),warningLevel:river==='Brahmaputra'?99.2:75,dangerLevel:river==='Brahmaputra'?100.2:76,trend:i%2?'STEADY':'RISING',floodStatus:i%2?'ABOVE NORMAL':'WARNING',sourceType:'CACHED',sourceName:'CWC Flood Forecasting Network'}));
 for(let i=1;i<=4;i++){for(const [type,label,off] of [['HOSPITAL','District Hospital',600],['POLICE','Police Station',650],['FIRE_STATION','Fire & Emergency Station',700]]){const p=point(c,off+i,.12);x.infrastructure.push({_id:id(),name:`${d.name} ${label} ${i}`,type,...p,status:'OPERATIONAL',district:d.name,state:d.state,sourceType:'DEMO',sourceName:'FloodGuard Seed'})}}
 for(let i=1;i<=4;i++)x.floodzones.push({_id:id(),name:`${d.name} Flood Affected Zone ${i}`,severity:i===1?'CRITICAL':i===2?'HIGH':'MODERATE',geometry:{type:'Polygon',coordinates:[[[c.lng-.035,c.lat-.035],[c.lng+.035,c.lat-.018],[c.lng+.02,c.lat+.035],[c.lng-.028,c.lat+.025],[c.lng-.035,c.lat-.035]]]},sourceType:'DEMO',sourceName:'FloodGuard Seed'});
 x.evacuations=[1,2,3].map((i)=>({_id:id(),zone:d.zones[i%d.zones.length],population:40+i*25,targetShelter:x.shelters[i-1]?._id,targetShelterName:x.shelters[i-1]?.name,assignedTeams:[x.resources[i-1]?._id],status:'ACTIVE',evacuated:i===1?18:0,state:d.state,district:d.name,public:true,sourceType:'DEMO',sourceName:'FloodGuard Seed',createdAt:new Date(Date.now()-i*45*60000)}));
 x.alerts=[{_id:id(),title:`${d.name} flood situation watch`,description:'Demo operational advisory: monitor river levels, low-lying areas, road access and relief capacity.',severity:'WARNING',district:d.name,state:d.state,issuedAt:new Date(Date.now()-45*60000),expiresAt:new Date(Date.now()+8*3600000),sourceType:'DEMO',source:'FloodGuard Seed',officialUrl:'https://sachet.ndma.gov.in/'},{_id:id(),title:'Public flood preparedness notice',description:'Fallback operational notice. Not an official government warning.',severity:'WATCH',district:d.name,state:d.state,issuedAt:new Date(),sourceType:'DEMO',source:'FloodGuard Seed'}];
 return x}
function ensure(){if(ready)return store;for(const d of DISTRICTS)store[`${d.state}::${d.name}`]=initDistrict(d);ready=true;return store}
function get(state,district){ensure();return store[`${state}::${district}`]||store['Uttar Pradesh::Lucknow']}
function addReport(state,district,report,incident){const d=get(state,district);d.reports.unshift({...report,_id:id(),incident});d.incidents.unshift(incident);return {report:d.reports[0],incident}}
module.exports={ensure,get,addReport};
